# Javascript Node CircleCI 2.0 configuration file
#
# Trigger URL to run tests on circle ci is: https://circleci.com/api/v1.1/project/github/system_test/tree/master?circle-token={{CIRCLE_TOKEN}}


version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10.1-browsers

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      # - persist_to_workspace:
      #     root: ~/
      #     paths:
      #       - repo # persist working directory

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run tests!
      - run: |
        if [ -n "${ENV}" = "production" ]
        then
          echo "Running integration test on production"
          yarn test
        else if [ -n "${ENV}" = "stage" ]
        then
          echo "Running integration test on stage"
          yarn test
        else if [ -n "${ENV}" = "test" ]
          echo "Not running integration test. This is just a test."
        else
          echo "ENV variable not set. Please set ENV to 'production', 'stage' or 'test'"
        fi
  # test:
  #   docker:
  #     - image: circleci/node:7.10.1-browsers

  #   working_directory: ~/repo # Use same WD as build

  #   steps:
  #     - attach_workspace:
  #         at: ~/
  #     - run:
  #         name: Integration Test
  #         command: yarn test
# workflows:
#   version: 2
#   integration_test:
#     jobs:
#       - build
#       - test:
#           requires:
#             - build
